name:                emacs-diary-convert
version:             0.1.0.0
github:              "githubuser/emacs-diary-convert"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.org

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/githubuser/emacs-diary-convert#readme>

dependencies:
- base >= 4.7 && < 5
- parsec

library:
  source-dirs: src

executables:
  emacs-diary-convert-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - emacs-diary-convert

tests:
  emacs-diary-convert-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - emacs-diary-convert
